### ISSUE TITLE
Buggy drop down menu for sound and wifi menu

### ISSUE THREAD

**Issue by coreybruce** [raboof/xfce4-panel#1]
When elements change in wifi like new detected wifi or more added players or opened players the drop down menu will appear over the panel or off the panel, this has been a on going issue for a long time on XFCE/Xubuntu

**Comment by raboof** [comment]
This repository is just a fork, you probably want to report this upstream at https://bugzilla.xfce.org/ :)

**Comment by coreybruce** [comment]
@raboof ok thanks, I really would like this fixed :)
