### ISSUE TITLE
Taskbar behavior like in Windows 7?

### ISSUE THREAD

**Issue by ghost** [raboof/xfce4-panel#2]
Hi, instead of having it launch another instance somewhere else in the panel is it possible that the launched program sticks to being where the launcher is? I'm talking about this.

![deepinscreenshot_select-area_20170930222600](https://user-images.githubusercontent.com/18366085/31049193-655c1b06-a62e-11e7-8fb3-d21a4bae7688.png)

**Comment by raboof** [comment]
Hi @skullscream, this repository is not the 'real' xfce4-panel repository, just a fork I made to publish a [tweak](https://github.com/raboof/xfce4-panel/commit/6aa5a065b187d09564392f0fab277a1e27df6d73)
