### ISSUE TITLE
Won't work with --pointer

### ISSUE THREAD

**Issue by sispus** [raboof/xfce4-panel#3]
Hi,
In manjaro after upgrading xfce 4.14, command `xfce4-popup-windowmenu -p` stopped working.
 `xfce4-popup-windowmenu -V` and `xfce4-popup-windowmenu -`h works.

the same problem exists with `xfce4-popup-dirmenu -p` but not with `xfce4-popup-whiskermenu -p`

**Comment by raboof** [comment]
Hi! This is a private fork of xfce4-panel, and it looks like this is an issue with the official upstream - so you probably want to file it over there ;)
